[ClassVersion("0.1.0.0"), FriendlyName("xPendingReboot")] 
class MSFT_xPendingReboot : OMI_BaseResource
{
  [key] string Name;
  [write] boolean SkipComponentBasedServicing;
  [read] boolean ComponentBasedServicing;

  [write] boolean SkipWindowsUpdate;
  [read] boolean WindowsUpdate;

  [write] boolean SkipPendingFileRename;
  [read] boolean PendingFileRename;

  [write] boolean SkipPendingComputerRename;
  [read] boolean PendingComputerRename;

  [write] boolean SkipCcmClientSDK;
  [read] boolean CcmClientSDK;
};

